### PR TITLE
Basic all in one script

### PR DESCRIPTION
**Pull request by lewisjared**
## Description

Adds a basic script to run all of the required steps via a single script. This is useful for testing the image as a whole @mikapfl 

This script (`scripts/run-wrf.sh`) should be set as the command when running the container.

## Checklist

Please confirm that this pull request has done the following:

- [ ] Tests added
- [ ] Documentation added (where applicable)

### CODE REVIEW

**Comment by lewisjared** [comment]
This is currently untested, but a decent starting point

**Review by mikapfl — APPROVED** [review]

**Comment by lewisjared** [comment]
This is on hold until #22 is resolved

**Comment by mikapfl** [comment]
Just trying to understand the whole process better: Do we expect to cache something which `setup_for_wrf.py` does in the "real" workflow? Or do we expect that we start from a completely clean slate every time? I guess what I'm asking is: does this have any *input* which needs to be mounted to a specific path or something?

**Comment by lewisjared** [comment]
With the repo reshuffle this particular job may change slightly with the last line (running setup_for_cmaq.py) being moved to the openmethane repository in which case the `data/wrf` directory is the key output of the job

**Pull request merged**
